### ISSUE TITLE
Polygon failed to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by spvkgn** [shmuz/LuaFAR-2L#9]
Возможно причина в версии sqlite3 (3.22.0)
```
[ 89%] Building C object Plugins/polygon/CMakeFiles/polygon.dir/tmp/build/far2m/luafar/src/luaplug.c.o
cd /tmp/build/luafar2m/_build/Plugins/polygon && /usr/bin/cc -DEXPORT_CLOSEPLUGIN -DEXPORT_CONFIGURE -DEXPORT_DELETEFILES -DEXPORT_FREEFINDDATA -DEXPORT_GETFINDDATA -DEXPORT_GETOPENPLUGININFO -DEXPORT_OPENFILEPLUGIN -DEXPORT_OPENPLUGIN -DEXPORT_PROCESSEVENT -DEXPORT_PROCESSKEY -DEXPORT_SETDIRECTORY -Dpolygon_EXPORTS -I/usr/include/luajit-2.1 -I/tmp/build/luafar2m/../far2m/WinPort -I/tmp/build/luafar2m/../far2m/far/far2sdk -I/tmp/build/luafar2m/../far2m/luafar/src  -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -ffunction-sections -fdata-sections -Wl,--gc-sections -DFUNC_OPENLIBS=luaopen_polygon  -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -O2 -fPIC -fvisibility=hidden   -std=gnu11 -o CMakeFiles/polygon.dir/tmp/build/far2m/luafar/src/luaplug.c.o   -c /tmp/build/far2m/luafar/src/luaplug.c
/tmp/build/luafar2m/Plugins/polygon/src/lsqlite3.c: In function 'db_create_module':
/tmp/build/luafar2m/Plugins/polygon/src/lsqlite3.c:3270:15: error: 'sqlite3_module {aka struct sqlite3_module}' has no member named 'xShadowName'
         module->Name = Name;               \
               ^
/tmp/build/luafar2m/Plugins/polygon/src/lsqlite3.c:3335:5: note: in expansion of macro 'SETPOINTER'
     SETPOINTER(xShadowName)
     ^~~~~~~~~~
Plugins/polygon/CMakeFiles/polygon.dir/build.make:113: recipe for target 'Plugins/polygon/CMakeFiles/polygon.dir/src/lsqlite3.c.o' failed
```

**Comment by shmuz** [comment]
Как-то я проверял минимально необходимую версию и записал в хелп
`The plugin requires an external sqlite3.dll (version >= 3.22)`
А на Убунту 18.04 какая версия SQLite3 ? 3.22.0 ?

**Comment by shmuz** [comment]
Сейчас проверил: `xShadowName` было добавлено в SQLite3 в ноябре 2018 года.
Это значит, что минимальная версия 3.26.0.

Теперь вопрос:
- возможно ли с этим справиться в проекте portable
- или только в плагине с помощью анализа версии SQLite ?

**Comment by shmuz** [comment]
Ну я в любом случае обязан разобраться :)

**Comment by shmuz** [comment]
@spvkgn 
Просьба ничего пока не предпринимать, в плагине явный баг.

**Comment by shmuz** [comment]
Пожалуйста проверьте сейчас c Ubuntu 18.04 и SQLite 3.22.0.

**Comment by shmuz** [comment]
Спасибо!
